### PR TITLE
Added Queue Creation Animation.

### PR DESCRIPTION
**Pull request by Diallo**
Simply a couple of changes to have the queues added a bit more nicely. 

Added the animation that allows for Queues to appear bottom-top when being loaded

### CODE REVIEW

**Comment by phillip-tian** [comment]
The functionality looks good, I was just wondering if there's a simpler/more efficient way of implementing the queue creation animation? [This link](https://low-scope.com/unity-quick-the-most-common-ways-to-move-a-object/) introduces some standard ways of implementing object movement, maybe check out the section on VECTOR3.MOVETOWARDS?

**Comment by lukasotocerny** [comment]
I agree with @phillip-tian that `Vector3.Movetowards` seems like a cleaner way of achieving exactly what your code does

**Review by lukasotocerny — CHANGES_REQUESTED** [review]
there's a merge conflict

**Comment by Diallo** [comment]
> there's a merge conflict

I know. This is not done.

**Comment by Diallo** [comment]
@lukasotocerny @phillip-tian see #60

**Pull request closed without merging**
