### PR TITLE
Able to trigger the QM Detail Window

### PR DESCRIPTION
**Pull request by yuexu-98**
I thought it is the Raycast problem. But actually, it is because of the Collider. 
Problem solved with oneline for each Block: `lowerBlock.AddComponent<MeshCollider>().convex = true;`
😆😂

In this Pull Request:
1. Click QM -> Show QM Detail Window
2. Change content type for API Key Field (hide the API)
3. Add unit test example
4. Add a Help Window

Update: Change to Right Mouse Click

### CODE REVIEW

**Review by lukasotocerny — DISMISSED** [review]
I'm afraid the QM click does not work as intended -> when I'm navigating (i.e. having mouse clicked down and then pressing WASD to navigate) as soon as my mouse points to a block, it interprets it as if I clicked on it and sidebar pops up. So we want to differentiate behaviour when navigating vs. clicking on a block.
Otherwise password, help button and test look great 👍

**Comment by yuexu-98** [comment]
> I'm afraid the QM click does not work as intended -> when I'm navigating (i.e. having mouse clicked down and then pressing WASD to navigate) as soon as my mouse points to a block, it interprets it as if I clicked on it and sidebar pops up. So we want to differentiate behaviour when navigating vs. clicking on a block.
> Otherwise password, help button and test look great 👍

Do you think it would be more appropriate to change it to double-click?

**Comment by yuexu-98** [comment]
> > I'm afraid the QM click does not work as intended -> when I'm navigating (i.e. having mouse clicked down and then pressing WASD to navigate) as soon as my mouse points to a block, it interprets it as if I clicked on it and sidebar pops up. So we want to differentiate behaviour when navigating vs. clicking on a block.
> > Otherwise password, help button and test look great 👍
> 
> Do you think it would be more appropriate to change it to double-click?

Change to Right Mouse Click

**Review by phillip-tian — APPROVED** [review]
LGTM

**Pull request merged**
