### PR TITLE
Channels and applications dynamic update

### PR DESCRIPTION
**Pull request by Orange0719**

### CODE REVIEW

**Comment by lukasotocerny** [comment]
@phillip-tian Could you please have a look at this? I'm seeing some errors with `Outline` and the `QueueManager` class might need some refactoring anyways

**Comment by phillip-tian** [comment]
Dynamic update for queue/channel/application should work well together with ```NameRenderer``` and ```HighlightRenderer``` now, also cleaned up code a little for readability.

**Review by lukasotocerny — CHANGES_REQUESTED** [review]
Thanks @phillip-tian for looking into this.
I've noticed that when dynamically adding new application/channel, we don't add it to the dependency graph, so dependencies are not shown then. Can we fix this?

**Comment by phillip-tian** [comment]
> Thanks @phillip-tian for looking into this.
> I've noticed that when dynamically adding new application/channel, we don't add it to the dependency graph, so dependencies are not shown then. Can we fix this?

On it

**Review by lukasotocerny — APPROVED** [review]
LGTM

**Pull request merged**
