### PR TITLE
QM Details Window & Queue List Window: Able to get the details, generate the list

### PR DESCRIPTION
**Pull request by yuexu-98**
- Able to retrieve the corresponding QM information given the QM name
- Information panel for queue manager and table for lists of queues (may delete some properties later)
- Able to generate a table of queues given the number of queues
- Able to show the queue names

NOTICE:
- there is a test button for triggering the QM details window

Further Improvement:
- UI
- the transmission between these two windows

### CODE REVIEW

**Comment by yuexu-98** [comment]
image
I would keep all the retrieved attribute names at this stage. (Easier to remove unnecessary attributes later)

**Comment by yuexu-98** [comment]
image
Table for queue list

**Comment by yuexu-98** [comment]
image
Able to generate the queue list.
Will add some details to the UI later

**Review by lukasotocerny — APPROVED** [review]
LGTM 👍

**Pull request merged**
